name: prosthetic_ar_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.5.0  # Changed this version
  vector_math: ^2.1.4
  shared_preferences: ^2.2.2
  flutter_cube: ^0.1.1
  google_fonts: ^4.0.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.8.12
  image_picker: ^1.0.7
  http: ^1.1.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/