name: prosthetic_ar_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ar_flutter_plugin: ^0.7.3
  vector_math: ^2.1.0
  shared_preferences: ^2.0.15
  flutter_cube: ^0.1.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_fonts: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/triangle.png
    - assets/prosthetic_leg.obj
    - assets/detailed_prosthetic_leg.obj
    - assets/experiment.obj
    - assets/first.mtl